baseURL = "https://jirepository.com/"
locale = "en-us"
title = "repository"
theme = "sans"

[params]
  description = "a minimal blog"
  author = "ji"
  showDarkModeToggle = true
  showSearchIcon = true
  showGoToTop = true

  [params.homepage]
    onlyPostsInHomePage = false
    homePageLogo = false
    homePageTitle = ":D"
    homePageTagLine = "垃圾桶"
    homePageAbout = "hello, doodles, etc"
    homePageSummaryLength = 500
    homePagePostDate = false
    dateFormat = "2 Jan 2006"
    showSocialLinksHome = false

  [params.theme]
    heroSectionColor = "white"
    darkHeroSectionColor = "black"

  [params.posts]
    readingSpeed = 200

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 3

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"