baseURL = "https://jirepository.com/"
locale = "en-us"
title = "repo:ji"
theme = "sans"

[params]
  description = "a minimal blog"
  author = "ji"
  showDarkModeToggle = true    # <-- Put these right here!
  showSearchIcon = true
  showGoToTop = true

  [params.posts]
    readingSpeed = 200

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"